### ISSUE TITLE
Failed in installation

### ISSUE THREAD

**Issue by renee9904** [PoonLab/OpenRDP#35]
Hi PoonLab, I have met some problems when installing OpenRDP.
when I run `sudo python3 setup.py install`, it got`UserWarning: Unknown distribution option: 'define_macros'` with many warnings and `KeyError: '/mp-plvphf17'` I am hoping you can help me solve this problem and really looking forward to using your program.

**Comment by ArtPoon** [comment]
Sorry that you’re running into issues at installation. What OS and version of Oython are you using?

**Comment by ArtPoon** [comment]
Also please provide versions of Python module dependencies, e.g., NumPy

**Comment by renee9904** [comment]
Thank you for your reply. My Python version is 3.10.9, Scipy is 1.9.3, and NumPy is 1.23.5.

**Comment by ArtPoon** [comment]
Thanks - and your operating system?

**Comment by ArtPoon** [comment]
I've created a virtual environment to try to reproduce your issue:
```python
(venv) art@orolo:~/git/OpenRDP/iss35/venv$ python
Python 3.10.9 (main, Feb  2 2023, 22:27:01) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.23.5'
>>> import scipy
>>> scipy.__version__
'1.9.3'
```

Within this venv, I was not able to reproduce the error messages you reported, *but* I did encounter problems with building and installing OpenRDP with the setup script.  It looks like the problem is that the dependencies statement is too restrictive.  Please open `setup.py` in a text editor and replace the following:
```python
    install_requires=[
        'scipy>=1.5.0,<1.6.0',
        'numpy>=1.17.4,<1.20.0',
    ],
```

with this:
```python
    install_requires=[
        'scipy>=1.5.0',
        'numpy>=1.17.4',
    ],
```

and try running `sudo python3 setup.py install` again.
Note the above change to `setup.py` has already been incorporated into one of our development branches.

**Comment by renee9904** [comment]
It worked!! Thank you very much!

**Comment by ArtPoon** [comment]
Glad to hear it worked for you!  I am working on improving the user interface, so please keep an eye on this site for updates.
